version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: alibaba
        container_name: Alibaba
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=alibaba
            - DB_USERNAME=postgres
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: your_database_username
            POSTGRES_PASSWORD: your_database_password
            POSTGRES_DB: your_database_name
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
